-- testflow.dbo.ASSET_CLASSIFICATION definition

-- Drop table

-- DROP TABLE testflow.dbo.ASSET_CLASSIFICATION;

CREATE TABLE testflow.dbo.ASSET_CLASSIFICATION (
	ASSET_CLASSIFICATION_OID bigint NOT NULL,
	ATTR_NAME varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LEVEL_1 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LEVEL_2 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LEVEL_3 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT ASSET_CLASSIFICATION_PK PRIMARY KEY (ASSET_CLASSIFICATION_OID)
);


-- testflow.dbo.BANK definition

-- Drop table

-- DROP TABLE testflow.dbo.BANK;

CREATE TABLE testflow.dbo.BANK (
	BANK_OID decimal(25,0) NOT NULL,
	BANK_CODE_1 varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BANK_CODE_2 varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESCPT_LANG0 varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESCPT_LANG1 varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PREV_BUSSINESS_DATE date NULL,
	BUSINESS_DATE date NULL,
	NEXT_BUSINESS_DATE date NULL,
	LAST_MOD_DATETIME datetime NULL,
	LAST_MOD_USER varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DEFAULT_BRANCH_CODE varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT BANK_PK PRIMARY KEY (BANK_OID)
);


-- testflow.dbo.BATCH_BUSINESS_DATE_RESULT definition

-- Drop table

-- DROP TABLE testflow.dbo.BATCH_BUSINESS_DATE_RESULT;

CREATE TABLE testflow.dbo.BATCH_BUSINESS_DATE_RESULT (
	BATCH_BUSINESS_DATE_RESULT_OID decimal(25,0) NOT NULL,
	[TYPE] varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STATUS varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PREV_BUSINESS_DATE date NOT NULL,
	CREATE_BUSINESS_DATE date NOT NULL,
	SYSTEM_DATE date NOT NULL,
	CONSTRAINT BATCH_BUSINESS_DATE_RESULT_PK PRIMARY KEY (BATCH_BUSINESS_DATE_RESULT_OID)
);


-- testflow.dbo.BPM_CATEGORY definition

-- Drop table

-- DROP TABLE testflow.dbo.BPM_CATEGORY;

CREATE TABLE testflow.dbo.BPM_CATEGORY (
	ID bigint IDENTITY(1,1) NOT NULL,
	NAME nvarchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
	CODE nvarchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
	DESCRIPTION nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NOT NULL,
	STATUS tinyint DEFAULT NULL NULL,
	SORT int DEFAULT NULL NULL,
	CREATOR nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
	CREATE_TIME datetime2 DEFAULT getdate() NOT NULL,
	UPDATER nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
	UPDATE_TIME datetime2 DEFAULT getdate() NOT NULL,
	DELETED bit DEFAULT 0 NOT NULL,
	TENANT_ID bigint DEFAULT 0 NOT NULL,
	CONSTRAINT PK__BPM_CATE__3214EC2759EC8901 PRIMARY KEY (ID)
);


-- testflow.dbo.BPM_PROCESS_DEFINITION_INFO definition

-- Drop table

-- DROP TABLE testflow.dbo.BPM_PROCESS_DEFINITION_INFO;

CREATE TABLE testflow.dbo.BPM_PROCESS_DEFINITION_INFO (
	ID bigint IDENTITY(1,1) NOT NULL,
	PROCESS_DEFINITION_ID nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	MODEL_ID nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	MODEL_TYPE tinyint DEFAULT 10 NOT NULL,
	CATEGORY nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ICON nvarchar(512) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT NULL NULL,
	DESCRIPTION nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT NULL NULL,
	FORM_TYPE tinyint NOT NULL,
	FORM_ID bigint DEFAULT NULL NULL,
	FORM_CONF nvarchar(1000) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT NULL NULL,
	FORM_FIELDS nvarchar(4000) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT NULL NULL,
	FORM_CUSTOM_CREATE_PATH nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT NULL NULL,
	FORM_CUSTOM_VIEW_PATH nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT NULL NULL,
	SIMPLE_MODEL nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SORT bigint DEFAULT 0 NULL,
	VISIBLE varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '1' NOT NULL,
	START_USER_IDS nvarchar(256) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT NULL NULL,
	START_DEPT_IDS nvarchar(256) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT NULL NULL,
	MANAGER_USER_IDS nvarchar(256) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT NULL NULL,
	ALLOW_CANCEL_RUNNING_PROCESS varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '1' NOT NULL,
	PROCESS_ID_RULE nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT NULL NULL,
	AUTO_APPROVAL_TYPE tinyint DEFAULT 0 NOT NULL,
	TITLE_SETTING nvarchar(512) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT NULL NULL,
	SUMMARY_SETTING nvarchar(512) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT NULL NULL,
	PROCESS_BEFORE_TRIGGER_SETTING nvarchar(1024) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT NULL NULL,
	PROCESS_AFTER_TRIGGER_SETTING nvarchar(1024) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT NULL NULL,
	TASK_BEFORE_TRIGGER_SETTING nvarchar(1024) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT NULL NULL,
	TASK_AFTER_TRIGGER_SETTING nvarchar(1024) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT NULL NULL,
	CREATOR nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
	CREATE_TIME datetime2 DEFAULT getdate() NOT NULL,
	UPDATER nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
	UPDATE_TIME datetime2 DEFAULT getdate() NOT NULL,
	DELETED bit DEFAULT 0 NOT NULL,
	TENANT_ID bigint DEFAULT 0 NOT NULL,
	CONSTRAINT PK__BPM_PROC__3214EC277CED2397 PRIMARY KEY (ID)
);


-- testflow.dbo.BR_BENCHMARK_MODEL_INFO definition

-- Drop table

-- DROP TABLE testflow.dbo.BR_BENCHMARK_MODEL_INFO;

CREATE TABLE testflow.dbo.BR_BENCHMARK_MODEL_INFO (
	ID int IDENTITY(1,1) NOT NULL,
	CREATE_TIME datetime NOT NULL,
	BUSINESS_ID nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TYPE] nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NAME nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PROVIDER nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MODEL_FAMILY nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	VENDOR nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK__BR_BENCH__3214EC279375BEF8 PRIMARY KEY (ID)
);


-- testflow.dbo.BR_BENCHMARK_MODEL_INFO_1 definition

-- Drop table

-- DROP TABLE testflow.dbo.BR_BENCHMARK_MODEL_INFO_1;

CREATE TABLE testflow.dbo.BR_BENCHMARK_MODEL_INFO_1 (
	ID int IDENTITY(1,1) NOT NULL,
	CREATE_TIME datetime NOT NULL,
	BUSINESS_ID nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TYPE] nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NAME nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PROVIDER nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MODEL_FAMILY nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	VENDOR_ID nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK__BR_BENCH__3214EC27082E31B0 PRIMARY KEY (ID)
);


-- testflow.dbo.BR_BENCHMARK_MODEL_INFO_2 definition

-- Drop table

-- DROP TABLE testflow.dbo.BR_BENCHMARK_MODEL_INFO_2;

CREATE TABLE testflow.dbo.BR_BENCHMARK_MODEL_INFO_2 (
	ID int IDENTITY(1,1) NOT NULL,
	CREATE_TIME datetime NOT NULL,
	BUSINESS_ID nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TYPE] nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NAME nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PROVIDER nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MODEL_FAMILY nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	VENDOR_ID nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK__BR_BENCH__3214EC27082E31B0_copy1 PRIMARY KEY (ID)
);


-- testflow.dbo.BR_COMPOSITE_WEIGHTS definition

-- Drop table

-- DROP TABLE testflow.dbo.BR_COMPOSITE_WEIGHTS;

CREATE TABLE testflow.dbo.BR_COMPOSITE_WEIGHTS (
	ID int IDENTITY(1,1) NOT NULL,
	CREATE_TIME datetime NOT NULL,
	[DATE] datetime NULL,
	BENCHMARK_ID nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COMPONENT_ID nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	WEIGHT numeric(20,2) NULL,
	CONSTRAINT PK__BR_COMPO__3214EC27CE9731C8 PRIMARY KEY (ID)
);


-- testflow.dbo.BR_COMPOSITE_WEIGHTS_1 definition

-- Drop table

-- DROP TABLE testflow.dbo.BR_COMPOSITE_WEIGHTS_1;

CREATE TABLE testflow.dbo.BR_COMPOSITE_WEIGHTS_1 (
	ID int IDENTITY(1,1) NOT NULL,
	CREATE_TIME datetime NOT NULL,
	[DATE] datetime NULL,
	BENCHMARK_ID nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COMPONENT_ID nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	WEIGHT decimal(20,2) NULL,
	CONSTRAINT PK__BR_COMPO__3214EC27DA41D97D PRIMARY KEY (ID)
);


-- testflow.dbo.BR_COMPOSITE_WEIGHTS_2 definition

-- Drop table

-- DROP TABLE testflow.dbo.BR_COMPOSITE_WEIGHTS_2;

CREATE TABLE testflow.dbo.BR_COMPOSITE_WEIGHTS_2 (
	ID int IDENTITY(1,1) NOT NULL,
	CREATE_TIME datetime NOT NULL,
	[DATE] datetime NULL,
	BENCHMARK_ID nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COMPONENT_ID nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	WEIGHT decimal(20,2) NULL,
	CONSTRAINT PK__BR_COMPO__3214EC27DA41D97D_copy1 PRIMARY KEY (ID)
);


-- testflow.dbo.BR_MODEL_INFO definition

-- Drop table

-- DROP TABLE testflow.dbo.BR_MODEL_INFO;

CREATE TABLE testflow.dbo.BR_MODEL_INFO (
	ID int IDENTITY(1,1) NOT NULL,
	CREATE_TIME datetime NOT NULL,
	BUSINESS_ID nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NAME nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TYPE] nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MODEL_VIEW nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK__BR_MODEL__3214EC27830A3EC0 PRIMARY KEY (ID)
);


-- testflow.dbo.BR_MODEL_INFO_1 definition

-- Drop table

-- DROP TABLE testflow.dbo.BR_MODEL_INFO_1;

CREATE TABLE testflow.dbo.BR_MODEL_INFO_1 (
	ID int IDENTITY(1,1) NOT NULL,
	CREATE_TIME datetime NOT NULL,
	BUSINESS_ID nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NAME nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TYPE] nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MODEL_VIEW nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK__BR_MODEL__3214EC2735F2B328 PRIMARY KEY (ID)
);


-- testflow.dbo.BR_MODEL_INFO_2 definition

-- Drop table

-- DROP TABLE testflow.dbo.BR_MODEL_INFO_2;

CREATE TABLE testflow.dbo.BR_MODEL_INFO_2 (
	ID int NULL,
	CREATE_TIME datetime NULL,
	BUSINESS_ID nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NAME nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TYPE] nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MODEL_VIEW nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
);


-- testflow.dbo.BR_MODEL_POSITION_DATA definition

-- Drop table

-- DROP TABLE testflow.dbo.BR_MODEL_POSITION_DATA;

CREATE TABLE testflow.dbo.BR_MODEL_POSITION_DATA (
	ID int IDENTITY(1,1) NOT NULL,
	CREATE_TIME datetime NOT NULL,
	POS_DATE datetime NULL,
	PORTFOLIO_ID nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLIENT_ID nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	WEIGHT numeric(20,2) NULL,
	CONSTRAINT PK__BR_MODEL__3214EC27167884F7 PRIMARY KEY (ID)
);


-- testflow.dbo.BR_MODEL_POSITION_DATA_1 definition

-- Drop table

-- DROP TABLE testflow.dbo.BR_MODEL_POSITION_DATA_1;

CREATE TABLE testflow.dbo.BR_MODEL_POSITION_DATA_1 (
	ID int IDENTITY(1,1) NOT NULL,
	CREATE_TIME datetime NOT NULL,
	POS_DATE datetime NULL,
	PORTFOLIO_ID nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLIENT_ID nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	WEIGHT numeric(20,2) NULL,
	CONSTRAINT PK__BR_MODEL__3214EC2745B8B125 PRIMARY KEY (ID)
);


-- testflow.dbo.BR_MODEL_POSITION_DATA_2 definition

-- Drop table

-- DROP TABLE testflow.dbo.BR_MODEL_POSITION_DATA_2;

CREATE TABLE testflow.dbo.BR_MODEL_POSITION_DATA_2 (
	ID int NULL,
	CREATE_TIME datetime NULL,
	POS_DATE datetime NULL,
	PORTFOLIO_ID nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLIENT_ID nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	WEIGHT numeric(20,2) NULL
);


-- testflow.dbo.BR_SECURITY_LIST definition

-- Drop table

-- DROP TABLE testflow.dbo.BR_SECURITY_LIST;

CREATE TABLE testflow.dbo.BR_SECURITY_LIST (
	ID int IDENTITY(1,1) NOT NULL,
	CREATE_TIME datetime NOT NULL,
	CLIENT_ID nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LIST_TAG nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LIST_VALUE nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK__BR_SECUR__3214EC273673E6B1 PRIMARY KEY (ID)
);


-- testflow.dbo.BR_SECURITY_LISTS_1 definition

-- Drop table

-- DROP TABLE testflow.dbo.BR_SECURITY_LISTS_1;

CREATE TABLE testflow.dbo.BR_SECURITY_LISTS_1 (
	ID int IDENTITY(1,1) NOT NULL,
	CREATE_TIME datetime NOT NULL,
	CLIENT_ID nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LIST_TAG nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LIST_VALUE nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DATA_SOURCE nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK__BR_SECUR__3214EC2705D2AF23 PRIMARY KEY (ID)
);


-- testflow.dbo.BR_SECURITY_LISTS_2 definition

-- Drop table

-- DROP TABLE testflow.dbo.BR_SECURITY_LISTS_2;

CREATE TABLE testflow.dbo.BR_SECURITY_LISTS_2 (
	ID int IDENTITY(1,1) NOT NULL,
	CREATE_TIME datetime NOT NULL,
	CLIENT_ID nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LIST_TAG nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LIST_VALUE nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DATA_SOURCE nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK__BR_SECUR__3214EC2705D2AF23_copy2 PRIMARY KEY (ID)
);


-- testflow.dbo.BR_SECURITY_MASTER_BND_1 definition

-- Drop table

-- DROP TABLE testflow.dbo.BR_SECURITY_MASTER_BND_1;

CREATE TABLE testflow.dbo.BR_SECURITY_MASTER_BND_1 (
	SECURITY_MASTER_OID bigint NOT NULL,
	CLIENT_ID nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CUSIP nvarchar(9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ISIN nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SEDOL nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TICKER nvarchar(16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRICE decimal(21,9) NULL,
	[DATE] date NULL,
	[SOURCE] nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLIENT_SEC_TYPE nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLIENT_SEC_TYPE2 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CD_INSTMT_TYPE nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT_HANT nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT_HANS nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ISSUE_COUNTRY nvarchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COUPON decimal(9,6) NULL,
	COUP_FREQ char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MATURITY date NULL,
	ISSUER nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MUNI_STATE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PUT_CALL nvarchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EXERCISE_TYPE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OPTION_STRIKE decimal(10,0) NULL,
	UNDERLYING_ID nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_ID_TYPE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_DESCRIPTION nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_PRICE decimal(10,0) NULL,
	CONTRACT_SIZE decimal(10,0) NULL,
	RIC nvarchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OCC nvarchar(21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FX_TRADE_DATE date NULL,
	FX_TRADE_CURRENCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NDF_TYPE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONTRACT_CODE nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STANDARD_CONTRACT char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ACCRUAL_DT date NULL,
	RED_CODE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EFFECTIVE_DATE date NULL,
	COUP_FREQ_PAY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COUP_FREQ_RCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY_PAY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY_RCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PAY_LEG nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REC_LEG nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FIXED_RATE decimal(10,0) NULL,
	UNDERLYING_TERM decimal(10,0) NULL,
	INDEX_NAME_PAY nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	INDEX_NAME_RVY nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TERM decimal(10,0) NULL,
	INDEX_NAME nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	IRS_TYPE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PROXY_SECTOR nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ATTR_NAME nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRODUCT_RISK_RATING decimal(1,0) NULL,
	CONSTRAINT PK__SECURITY__DB91FF368B7EDD25 PRIMARY KEY (SECURITY_MASTER_OID)
);


-- testflow.dbo.BR_SECURITY_MASTER_BND_2 definition

-- Drop table

-- DROP TABLE testflow.dbo.BR_SECURITY_MASTER_BND_2;

CREATE TABLE testflow.dbo.BR_SECURITY_MASTER_BND_2 (
	SECURITY_MASTER_OID bigint NOT NULL,
	CLIENT_ID nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CUSIP nvarchar(9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ISIN nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SEDOL nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TICKER nvarchar(16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRICE decimal(21,9) NULL,
	[DATE] date NULL,
	[SOURCE] nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLIENT_SEC_TYPE nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLIENT_SEC_TYPE2 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CD_INSTMT_TYPE nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT_HANT nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT_HANS nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ISSUE_COUNTRY nvarchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COUPON decimal(9,6) NULL,
	COUP_FREQ char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MATURITY date NULL,
	ISSUER nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MUNI_STATE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PUT_CALL nvarchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EXERCISE_TYPE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OPTION_STRIKE decimal(10,0) NULL,
	UNDERLYING_ID nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_ID_TYPE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_DESCRIPTION nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_PRICE decimal(10,0) NULL,
	CONTRACT_SIZE decimal(10,0) NULL,
	RIC nvarchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OCC nvarchar(21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FX_TRADE_DATE date NULL,
	FX_TRADE_CURRENCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NDF_TYPE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONTRACT_CODE nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STANDARD_CONTRACT char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ACCRUAL_DT date NULL,
	RED_CODE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EFFECTIVE_DATE date NULL,
	COUP_FREQ_PAY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COUP_FREQ_RCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY_PAY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY_RCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PAY_LEG nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REC_LEG nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FIXED_RATE decimal(10,0) NULL,
	UNDERLYING_TERM decimal(10,0) NULL,
	INDEX_NAME_PAY nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	INDEX_NAME_RVY nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TERM decimal(10,0) NULL,
	INDEX_NAME nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	IRS_TYPE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PROXY_SECTOR nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ATTR_NAME nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRODUCT_RISK_RATING decimal(1,0) NULL,
	CONSTRAINT PK__SECURITY__DB91FF368B7EDD25_copy1 PRIMARY KEY (SECURITY_MASTER_OID)
);


-- testflow.dbo.BR_SECURITY_MASTER_CBL_1 definition

-- Drop table

-- DROP TABLE testflow.dbo.BR_SECURITY_MASTER_CBL_1;

CREATE TABLE testflow.dbo.BR_SECURITY_MASTER_CBL_1 (
	SECURITY_MASTER_OID bigint NOT NULL,
	CLIENT_ID nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CUSIP nvarchar(9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ISIN nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SEDOL nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TICKER nvarchar(16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRICE decimal(21,9) NULL,
	[DATE] date NULL,
	[SOURCE] nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLIENT_SEC_TYPE nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLIENT_SEC_TYPE2 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CD_INSTMT_TYPE nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT_HANT nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT_HANS nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ISSUE_COUNTRY nvarchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COUPON decimal(9,6) NULL,
	COUP_FREQ char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MATURITY date NULL,
	ISSUER nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MUNI_STATE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PUT_CALL nvarchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EXERCISE_TYPE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OPTION_STRIKE decimal(10,0) NULL,
	UNDERLYING_ID nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_ID_TYPE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_DESCRIPTION nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_PRICE decimal(10,0) NULL,
	CONTRACT_SIZE decimal(10,0) NULL,
	RIC nvarchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OCC nvarchar(21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FX_TRADE_DATE date NULL,
	FX_TRADE_CURRENCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NDF_TYPE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONTRACT_CODE nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STANDARD_CONTRACT char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ACCRUAL_DT date NULL,
	RED_CODE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EFFECTIVE_DATE date NULL,
	COUP_FREQ_PAY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COUP_FREQ_RCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY_PAY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY_RCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PAY_LEG nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REC_LEG nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FIXED_RATE decimal(10,0) NULL,
	UNDERLYING_TERM decimal(10,0) NULL,
	INDEX_NAME_PAY nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	INDEX_NAME_RVY nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TERM decimal(10,0) NULL,
	INDEX_NAME nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	IRS_TYPE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PROXY_SECTOR nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ATTR_NAME nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRODUCT_RISK_RATING decimal(1,0) NULL,
	CONSTRAINT PK__SECURITY__DB91FF368B7EDD25_copy2 PRIMARY KEY (SECURITY_MASTER_OID)
);


-- testflow.dbo.BR_SECURITY_MASTER_COS_1 definition

-- Drop table

-- DROP TABLE testflow.dbo.BR_SECURITY_MASTER_COS_1;

CREATE TABLE testflow.dbo.BR_SECURITY_MASTER_COS_1 (
	SECURITY_MASTER_OID bigint NOT NULL,
	CLIENT_ID nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CUSIP nvarchar(9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ISIN nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SEDOL nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TICKER nvarchar(16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRICE decimal(21,9) NULL,
	[DATE] date NULL,
	[SOURCE] nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLIENT_SEC_TYPE nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLIENT_SEC_TYPE2 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CD_INSTMT_TYPE nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT_HANT nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT_HANS nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ISSUE_COUNTRY nvarchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COUPON decimal(9,6) NULL,
	COUP_FREQ char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MATURITY date NULL,
	ISSUER nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MUNI_STATE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PUT_CALL nvarchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EXERCISE_TYPE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OPTION_STRIKE decimal(10,0) NULL,
	UNDERLYING_ID nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_ID_TYPE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_DESCRIPTION nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_PRICE decimal(10,0) NULL,
	CONTRACT_SIZE decimal(10,0) NULL,
	RIC nvarchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OCC nvarchar(21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FX_TRADE_DATE date NULL,
	FX_TRADE_CURRENCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NDF_TYPE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONTRACT_CODE nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STANDARD_CONTRACT char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ACCRUAL_DT date NULL,
	RED_CODE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EFFECTIVE_DATE date NULL,
	COUP_FREQ_PAY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COUP_FREQ_RCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY_PAY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY_RCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PAY_LEG nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REC_LEG nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FIXED_RATE decimal(10,0) NULL,
	UNDERLYING_TERM decimal(10,0) NULL,
	INDEX_NAME_PAY nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	INDEX_NAME_RVY nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TERM decimal(10,0) NULL,
	INDEX_NAME nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	IRS_TYPE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PROXY_SECTOR nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ATTR_NAME nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRODUCT_RISK_RATING decimal(1,0) NULL,
	CONSTRAINT PK__SECURITY__DB91FF368B7EDD25_copy4 PRIMARY KEY (SECURITY_MASTER_OID)
);


-- testflow.dbo.BR_SECURITY_MASTER_COS_2 definition

-- Drop table

-- DROP TABLE testflow.dbo.BR_SECURITY_MASTER_COS_2;

CREATE TABLE testflow.dbo.BR_SECURITY_MASTER_COS_2 (
	SECURITY_MASTER_OID bigint NOT NULL,
	CLIENT_ID nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CUSIP nvarchar(9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ISIN nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SEDOL nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TICKER nvarchar(16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRICE decimal(21,9) NULL,
	[DATE] date NULL,
	[SOURCE] nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLIENT_SEC_TYPE nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLIENT_SEC_TYPE2 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CD_INSTMT_TYPE nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT_HANT nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT_HANS nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ISSUE_COUNTRY nvarchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COUPON decimal(9,6) NULL,
	COUP_FREQ char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MATURITY date NULL,
	ISSUER nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MUNI_STATE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PUT_CALL nvarchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EXERCISE_TYPE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OPTION_STRIKE decimal(10,0) NULL,
	UNDERLYING_ID nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_ID_TYPE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_DESCRIPTION nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_PRICE decimal(10,0) NULL,
	CONTRACT_SIZE decimal(10,0) NULL,
	RIC nvarchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OCC nvarchar(21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FX_TRADE_DATE date NULL,
	FX_TRADE_CURRENCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NDF_TYPE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONTRACT_CODE nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STANDARD_CONTRACT char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ACCRUAL_DT date NULL,
	RED_CODE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EFFECTIVE_DATE date NULL,
	COUP_FREQ_PAY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COUP_FREQ_RCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY_PAY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY_RCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PAY_LEG nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REC_LEG nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FIXED_RATE decimal(10,0) NULL,
	UNDERLYING_TERM decimal(10,0) NULL,
	INDEX_NAME_PAY nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	INDEX_NAME_RVY nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TERM decimal(10,0) NULL,
	INDEX_NAME nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	IRS_TYPE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PROXY_SECTOR nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ATTR_NAME nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRODUCT_RISK_RATING decimal(1,0) NULL,
	CONSTRAINT PK__SECURITY__DB91FF368B7EDD25_copy5 PRIMARY KEY (SECURITY_MASTER_OID)
);


-- testflow.dbo.BR_SECURITY_MASTER_FMS_1 definition

-- Drop table

-- DROP TABLE testflow.dbo.BR_SECURITY_MASTER_FMS_1;

CREATE TABLE testflow.dbo.BR_SECURITY_MASTER_FMS_1 (
	SECURITY_MASTER_OID bigint NOT NULL,
	CLIENT_ID nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CUSIP nvarchar(9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ISIN nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SEDOL nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TICKER nvarchar(16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRICE decimal(21,9) NULL,
	[DATE] date NULL,
	[SOURCE] nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLIENT_SEC_TYPE nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLIENT_SEC_TYPE2 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CD_INSTMT_TYPE nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT_HANT nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT_HANS nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ISSUE_COUNTRY nvarchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COUPON decimal(9,6) NULL,
	COUP_FREQ char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MATURITY date NULL,
	ISSUER nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MUNI_STATE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PUT_CALL nvarchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EXERCISE_TYPE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OPTION_STRIKE decimal(10,0) NULL,
	UNDERLYING_ID nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_ID_TYPE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_DESCRIPTION nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_PRICE decimal(10,0) NULL,
	CONTRACT_SIZE decimal(10,0) NULL,
	RIC nvarchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OCC nvarchar(21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FX_TRADE_DATE date NULL,
	FX_TRADE_CURRENCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NDF_TYPE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONTRACT_CODE nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STANDARD_CONTRACT char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ACCRUAL_DT date NULL,
	RED_CODE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EFFECTIVE_DATE date NULL,
	COUP_FREQ_PAY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COUP_FREQ_RCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY_PAY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY_RCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PAY_LEG nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REC_LEG nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FIXED_RATE decimal(10,0) NULL,
	UNDERLYING_TERM decimal(10,0) NULL,
	INDEX_NAME_PAY nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	INDEX_NAME_RVY nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TERM decimal(10,0) NULL,
	INDEX_NAME nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	IRS_TYPE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PROXY_SECTOR nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ATTR_NAME nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRODUCT_RISK_RATING decimal(1,0) NULL,
	CONSTRAINT PK__SECURITY__DB91FF368B7EDD25_copy6 PRIMARY KEY (SECURITY_MASTER_OID)
);


-- testflow.dbo.BR_SECURITY_MASTER_FMS_2 definition

-- Drop table

-- DROP TABLE testflow.dbo.BR_SECURITY_MASTER_FMS_2;

CREATE TABLE testflow.dbo.BR_SECURITY_MASTER_FMS_2 (
	SECURITY_MASTER_OID bigint NOT NULL,
	CLIENT_ID nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CUSIP nvarchar(9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ISIN nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SEDOL nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TICKER nvarchar(16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRICE decimal(21,9) NULL,
	[DATE] date NULL,
	[SOURCE] nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLIENT_SEC_TYPE nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLIENT_SEC_TYPE2 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CD_INSTMT_TYPE nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT_HANT nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT_HANS nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ISSUE_COUNTRY nvarchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COUPON decimal(9,6) NULL,
	COUP_FREQ char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MATURITY date NULL,
	ISSUER nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MUNI_STATE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PUT_CALL nvarchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EXERCISE_TYPE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OPTION_STRIKE decimal(10,0) NULL,
	UNDERLYING_ID nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_ID_TYPE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_DESCRIPTION nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_PRICE decimal(10,0) NULL,
	CONTRACT_SIZE decimal(10,0) NULL,
	RIC nvarchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OCC nvarchar(21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FX_TRADE_DATE date NULL,
	FX_TRADE_CURRENCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NDF_TYPE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONTRACT_CODE nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STANDARD_CONTRACT char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ACCRUAL_DT date NULL,
	RED_CODE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EFFECTIVE_DATE date NULL,
	COUP_FREQ_PAY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COUP_FREQ_RCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY_PAY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY_RCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PAY_LEG nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REC_LEG nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FIXED_RATE decimal(10,0) NULL,
	UNDERLYING_TERM decimal(10,0) NULL,
	INDEX_NAME_PAY nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	INDEX_NAME_RVY nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TERM decimal(10,0) NULL,
	INDEX_NAME nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	IRS_TYPE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PROXY_SECTOR nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ATTR_NAME nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRODUCT_RISK_RATING decimal(1,0) NULL,
	CONSTRAINT PK__SECURITY__DB91FF368B7EDD25_copy7 PRIMARY KEY (SECURITY_MASTER_OID)
);


-- testflow.dbo.BR_SECURITY_MASTER_MRG_1 definition

-- Drop table

-- DROP TABLE testflow.dbo.BR_SECURITY_MASTER_MRG_1;

CREATE TABLE testflow.dbo.BR_SECURITY_MASTER_MRG_1 (
	SECURITY_MASTER_OID bigint NOT NULL,
	CLIENT_ID nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CUSIP nvarchar(9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ISIN nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SEDOL nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TICKER nvarchar(16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRICE decimal(21,9) NULL,
	[DATE] date NULL,
	[SOURCE] nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLIENT_SEC_TYPE nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLIENT_SEC_TYPE2 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CD_INSTMT_TYPE nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT_HANT nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT_HANS nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ISSUE_COUNTRY nvarchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COUPON decimal(9,6) NULL,
	COUP_FREQ char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MATURITY date NULL,
	ISSUER nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MUNI_STATE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PUT_CALL nvarchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EXERCISE_TYPE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OPTION_STRIKE decimal(10,0) NULL,
	UNDERLYING_ID nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_ID_TYPE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_DESCRIPTION nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_PRICE decimal(10,0) NULL,
	CONTRACT_SIZE decimal(10,0) NULL,
	RIC nvarchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OCC nvarchar(21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FX_TRADE_DATE date NULL,
	FX_TRADE_CURRENCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NDF_TYPE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONTRACT_CODE nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STANDARD_CONTRACT char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ACCRUAL_DT date NULL,
	RED_CODE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EFFECTIVE_DATE date NULL,
	COUP_FREQ_PAY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COUP_FREQ_RCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY_PAY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY_RCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PAY_LEG nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REC_LEG nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FIXED_RATE decimal(10,0) NULL,
	UNDERLYING_TERM decimal(10,0) NULL,
	INDEX_NAME_PAY nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	INDEX_NAME_RVY nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TERM decimal(10,0) NULL,
	INDEX_NAME nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	IRS_TYPE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PROXY_SECTOR nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ATTR_NAME nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRODUCT_RISK_RATING decimal(1,0) NULL,
	CONSTRAINT PK__SECURITY__DB91FF368B7EDD25_copy8 PRIMARY KEY (SECURITY_MASTER_OID)
);


-- testflow.dbo.BR_SECURITY_MASTER_MRG_2 definition

-- Drop table

-- DROP TABLE testflow.dbo.BR_SECURITY_MASTER_MRG_2;

CREATE TABLE testflow.dbo.BR_SECURITY_MASTER_MRG_2 (
	SECURITY_MASTER_OID bigint NOT NULL,
	CLIENT_ID nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CUSIP nvarchar(9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ISIN nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SEDOL nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TICKER nvarchar(16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRICE decimal(21,9) NULL,
	[DATE] date NULL,
	[SOURCE] nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLIENT_SEC_TYPE nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLIENT_SEC_TYPE2 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CD_INSTMT_TYPE nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT_HANT nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT_HANS nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ISSUE_COUNTRY nvarchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COUPON decimal(9,6) NULL,
	COUP_FREQ char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MATURITY date NULL,
	ISSUER nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MUNI_STATE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PUT_CALL nvarchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EXERCISE_TYPE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OPTION_STRIKE decimal(10,0) NULL,
	UNDERLYING_ID nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_ID_TYPE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_DESCRIPTION nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_PRICE decimal(10,0) NULL,
	CONTRACT_SIZE decimal(10,0) NULL,
	RIC nvarchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OCC nvarchar(21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FX_TRADE_DATE date NULL,
	FX_TRADE_CURRENCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NDF_TYPE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONTRACT_CODE nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STANDARD_CONTRACT char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ACCRUAL_DT date NULL,
	RED_CODE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EFFECTIVE_DATE date NULL,
	COUP_FREQ_PAY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COUP_FREQ_RCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY_PAY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY_RCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PAY_LEG nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REC_LEG nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FIXED_RATE decimal(10,0) NULL,
	UNDERLYING_TERM decimal(10,0) NULL,
	INDEX_NAME_PAY nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	INDEX_NAME_RVY nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TERM decimal(10,0) NULL,
	INDEX_NAME nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	IRS_TYPE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PROXY_SECTOR nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ATTR_NAME nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRODUCT_RISK_RATING decimal(1,0) NULL,
	CONSTRAINT PK__SECURITY__DB91FF368B7EDD25_copy9 PRIMARY KEY (SECURITY_MASTER_OID)
);


-- testflow.dbo.BR_SECURITY_MASTER_MTC_1 definition

-- Drop table

-- DROP TABLE testflow.dbo.BR_SECURITY_MASTER_MTC_1;

CREATE TABLE testflow.dbo.BR_SECURITY_MASTER_MTC_1 (
	SECURITY_MASTER_OID bigint NOT NULL,
	CLIENT_ID nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CUSIP nvarchar(9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ISIN nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SEDOL nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TICKER nvarchar(16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRICE decimal(21,9) NULL,
	[DATE] date NULL,
	[SOURCE] nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLIENT_SEC_TYPE nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLIENT_SEC_TYPE2 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CD_INSTMT_TYPE nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT_HANT nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT_HANS nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ISSUE_COUNTRY nvarchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COUPON decimal(9,6) NULL,
	COUP_FREQ char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MATURITY date NULL,
	ISSUER nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MUNI_STATE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PUT_CALL nvarchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EXERCISE_TYPE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OPTION_STRIKE decimal(10,0) NULL,
	UNDERLYING_ID nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_ID_TYPE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_DESCRIPTION nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_PRICE decimal(10,0) NULL,
	CONTRACT_SIZE decimal(10,0) NULL,
	RIC nvarchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OCC nvarchar(21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FX_TRADE_DATE date NULL,
	FX_TRADE_CURRENCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NDF_TYPE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONTRACT_CODE nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STANDARD_CONTRACT char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ACCRUAL_DT date NULL,
	RED_CODE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EFFECTIVE_DATE date NULL,
	COUP_FREQ_PAY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COUP_FREQ_RCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY_PAY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY_RCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PAY_LEG nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REC_LEG nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FIXED_RATE decimal(10,0) NULL,
	UNDERLYING_TERM decimal(10,0) NULL,
	INDEX_NAME_PAY nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	INDEX_NAME_RVY nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TERM decimal(10,0) NULL,
	INDEX_NAME nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	IRS_TYPE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PROXY_SECTOR nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ATTR_NAME nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRODUCT_RISK_RATING decimal(1,0) NULL,
	CONSTRAINT PK__SECURITY__DB91FF368B7EDD25_copy10 PRIMARY KEY (SECURITY_MASTER_OID)
);


-- testflow.dbo.BR_SECURITY_MASTER_MTC_2 definition

-- Drop table

-- DROP TABLE testflow.dbo.BR_SECURITY_MASTER_MTC_2;

CREATE TABLE testflow.dbo.BR_SECURITY_MASTER_MTC_2 (
	SECURITY_MASTER_OID bigint NOT NULL,
	CLIENT_ID nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CUSIP nvarchar(9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ISIN nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SEDOL nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TICKER nvarchar(16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRICE decimal(21,9) NULL,
	[DATE] date NULL,
	[SOURCE] nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLIENT_SEC_TYPE nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLIENT_SEC_TYPE2 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CD_INSTMT_TYPE nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT_HANT nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT_HANS nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ISSUE_COUNTRY nvarchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COUPON decimal(9,6) NULL,
	COUP_FREQ char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MATURITY date NULL,
	ISSUER nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MUNI_STATE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PUT_CALL nvarchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EXERCISE_TYPE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OPTION_STRIKE decimal(10,0) NULL,
	UNDERLYING_ID nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_ID_TYPE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_DESCRIPTION nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_PRICE decimal(10,0) NULL,
	CONTRACT_SIZE decimal(10,0) NULL,
	RIC nvarchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OCC nvarchar(21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FX_TRADE_DATE date NULL,
	FX_TRADE_CURRENCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NDF_TYPE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONTRACT_CODE nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STANDARD_CONTRACT char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ACCRUAL_DT date NULL,
	RED_CODE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EFFECTIVE_DATE date NULL,
	COUP_FREQ_PAY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COUP_FREQ_RCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY_PAY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY_RCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PAY_LEG nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REC_LEG nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FIXED_RATE decimal(10,0) NULL,
	UNDERLYING_TERM decimal(10,0) NULL,
	INDEX_NAME_PAY nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	INDEX_NAME_RVY nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TERM decimal(10,0) NULL,
	INDEX_NAME nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	IRS_TYPE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PROXY_SECTOR nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ATTR_NAME nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRODUCT_RISK_RATING decimal(1,0) NULL,
	CONSTRAINT PK__SECURITY__DB91FF368B7EDD25_copy11 PRIMARY KEY (SECURITY_MASTER_OID)
);


-- testflow.dbo.BR_SECURITY_MASTER_PDS_1 definition

-- Drop table

-- DROP TABLE testflow.dbo.BR_SECURITY_MASTER_PDS_1;

CREATE TABLE testflow.dbo.BR_SECURITY_MASTER_PDS_1 (
	SECURITY_MASTER_OID bigint NOT NULL,
	CLIENT_ID nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CUSIP nvarchar(9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ISIN nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SEDOL nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TICKER nvarchar(16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRICE decimal(21,9) NULL,
	[DATE] date NULL,
	[SOURCE] nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLIENT_SEC_TYPE nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLIENT_SEC_TYPE2 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CD_INSTMT_TYPE nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT_HANT nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT_HANS nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ISSUE_COUNTRY nvarchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COUPON decimal(9,6) NULL,
	COUP_FREQ char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MATURITY date NULL,
	ISSUER nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MUNI_STATE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PUT_CALL nvarchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EXERCISE_TYPE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OPTION_STRIKE decimal(10,0) NULL,
	UNDERLYING_ID nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_ID_TYPE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_DESCRIPTION nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_PRICE decimal(10,0) NULL,
	CONTRACT_SIZE decimal(10,0) NULL,
	RIC nvarchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OCC nvarchar(21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FX_TRADE_DATE date NULL,
	FX_TRADE_CURRENCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NDF_TYPE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONTRACT_CODE nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STANDARD_CONTRACT char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ACCRUAL_DT date NULL,
	RED_CODE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EFFECTIVE_DATE date NULL,
	COUP_FREQ_PAY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COUP_FREQ_RCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY_PAY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY_RCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PAY_LEG nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REC_LEG nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FIXED_RATE decimal(10,0) NULL,
	UNDERLYING_TERM decimal(10,0) NULL,
	INDEX_NAME_PAY nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	INDEX_NAME_RVY nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TERM decimal(10,0) NULL,
	INDEX_NAME nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	IRS_TYPE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PROXY_SECTOR nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ATTR_NAME nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRODUCT_RISK_RATING decimal(1,0) NULL,
	CONSTRAINT PK__SECURITY__DB91FF368B7EDD25_copy12 PRIMARY KEY (SECURITY_MASTER_OID)
);


-- testflow.dbo.BR_SECURITY_MASTER_PDS_2 definition

-- Drop table

-- DROP TABLE testflow.dbo.BR_SECURITY_MASTER_PDS_2;

CREATE TABLE testflow.dbo.BR_SECURITY_MASTER_PDS_2 (
	SECURITY_MASTER_OID bigint NOT NULL,
	CLIENT_ID nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CUSIP nvarchar(9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ISIN nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SEDOL nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TICKER nvarchar(16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRICE decimal(21,9) NULL,
	[DATE] date NULL,
	[SOURCE] nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLIENT_SEC_TYPE nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLIENT_SEC_TYPE2 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CD_INSTMT_TYPE nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT_HANT nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT_HANS nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ISSUE_COUNTRY nvarchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COUPON decimal(9,6) NULL,
	COUP_FREQ char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MATURITY date NULL,
	ISSUER nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MUNI_STATE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PUT_CALL nvarchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EXERCISE_TYPE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OPTION_STRIKE decimal(10,0) NULL,
	UNDERLYING_ID nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_ID_TYPE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_DESCRIPTION nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_PRICE decimal(10,0) NULL,
	CONTRACT_SIZE decimal(10,0) NULL,
	RIC nvarchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OCC nvarchar(21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FX_TRADE_DATE date NULL,
	FX_TRADE_CURRENCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NDF_TYPE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONTRACT_CODE nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STANDARD_CONTRACT char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ACCRUAL_DT date NULL,
	RED_CODE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EFFECTIVE_DATE date NULL,
	COUP_FREQ_PAY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COUP_FREQ_RCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY_PAY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY_RCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PAY_LEG nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REC_LEG nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FIXED_RATE decimal(10,0) NULL,
	UNDERLYING_TERM decimal(10,0) NULL,
	INDEX_NAME_PAY nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	INDEX_NAME_RVY nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TERM decimal(10,0) NULL,
	INDEX_NAME nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	IRS_TYPE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PROXY_SECTOR nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ATTR_NAME nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRODUCT_RISK_RATING decimal(1,0) NULL,
	CONSTRAINT PK__SECURITY__DB91FF368B7EDD25_copy13 PRIMARY KEY (SECURITY_MASTER_OID)
);


-- testflow.dbo.BR_SECURITY_MASTER_PVB_1 definition

-- Drop table

-- DROP TABLE testflow.dbo.BR_SECURITY_MASTER_PVB_1;

CREATE TABLE testflow.dbo.BR_SECURITY_MASTER_PVB_1 (
	SECURITY_MASTER_OID bigint NOT NULL,
	CLIENT_ID nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CUSIP nvarchar(9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ISIN nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SEDOL nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TICKER nvarchar(16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRICE decimal(21,9) NULL,
	[DATE] date NULL,
	[SOURCE] nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLIENT_SEC_TYPE nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLIENT_SEC_TYPE2 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CD_INSTMT_TYPE nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT_HANT nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT_HANS nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ISSUE_COUNTRY nvarchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COUPON decimal(9,6) NULL,
	COUP_FREQ char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MATURITY date NULL,
	ISSUER nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MUNI_STATE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PUT_CALL nvarchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EXERCISE_TYPE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OPTION_STRIKE decimal(10,0) NULL,
	UNDERLYING_ID nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_ID_TYPE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_DESCRIPTION nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_PRICE decimal(10,0) NULL,
	CONTRACT_SIZE decimal(10,0) NULL,
	RIC nvarchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OCC nvarchar(21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FX_TRADE_DATE date NULL,
	FX_TRADE_CURRENCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NDF_TYPE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONTRACT_CODE nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STANDARD_CONTRACT char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ACCRUAL_DT date NULL,
	RED_CODE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EFFECTIVE_DATE date NULL,
	COUP_FREQ_PAY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COUP_FREQ_RCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY_PAY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY_RCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PAY_LEG nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REC_LEG nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FIXED_RATE decimal(10,0) NULL,
	UNDERLYING_TERM decimal(10,0) NULL,
	INDEX_NAME_PAY nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	INDEX_NAME_RVY nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TERM decimal(10,0) NULL,
	INDEX_NAME nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	IRS_TYPE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PROXY_SECTOR nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ATTR_NAME nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRODUCT_RISK_RATING decimal(1,0) NULL,
	CONSTRAINT PK__SECURITY__DB91FF368B7EDD25_copy14 PRIMARY KEY (SECURITY_MASTER_OID)
);


-- testflow.dbo.BR_SECURITY_MASTER_PVB_2 definition

-- Drop table

-- DROP TABLE testflow.dbo.BR_SECURITY_MASTER_PVB_2;

CREATE TABLE testflow.dbo.BR_SECURITY_MASTER_PVB_2 (
	SECURITY_MASTER_OID bigint NOT NULL,
	CLIENT_ID nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CUSIP nvarchar(9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ISIN nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SEDOL nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TICKER nvarchar(16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRICE decimal(21,9) NULL,
	[DATE] date NULL,
	[SOURCE] nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLIENT_SEC_TYPE nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLIENT_SEC_TYPE2 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CD_INSTMT_TYPE nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT_HANT nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT_HANS nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ISSUE_COUNTRY nvarchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COUPON decimal(9,6) NULL,
	COUP_FREQ char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MATURITY date NULL,
	ISSUER nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MUNI_STATE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PUT_CALL nvarchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EXERCISE_TYPE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OPTION_STRIKE decimal(10,0) NULL,
	UNDERLYING_ID nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_ID_TYPE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_DESCRIPTION nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_PRICE decimal(10,0) NULL,
	CONTRACT_SIZE decimal(10,0) NULL,
	RIC nvarchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OCC nvarchar(21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FX_TRADE_DATE date NULL,
	FX_TRADE_CURRENCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NDF_TYPE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONTRACT_CODE nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STANDARD_CONTRACT char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ACCRUAL_DT date NULL,
	RED_CODE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EFFECTIVE_DATE date NULL,
	COUP_FREQ_PAY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COUP_FREQ_RCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY_PAY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY_RCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PAY_LEG nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REC_LEG nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FIXED_RATE decimal(10,0) NULL,
	UNDERLYING_TERM decimal(10,0) NULL,
	INDEX_NAME_PAY nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	INDEX_NAME_RVY nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TERM decimal(10,0) NULL,
	INDEX_NAME nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	IRS_TYPE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PROXY_SECTOR nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ATTR_NAME nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRODUCT_RISK_RATING decimal(1,0) NULL,
	CONSTRAINT PK__SECURITY__DB91FF368B7EDD25_copy15 PRIMARY KEY (SECURITY_MASTER_OID)
);


-- testflow.dbo.BR_SECURITY_MASTER_SMS_1 definition

-- Drop table

-- DROP TABLE testflow.dbo.BR_SECURITY_MASTER_SMS_1;

CREATE TABLE testflow.dbo.BR_SECURITY_MASTER_SMS_1 (
	SECURITY_MASTER_OID bigint NOT NULL,
	CLIENT_ID nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CUSIP nvarchar(9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ISIN nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SEDOL nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TICKER nvarchar(16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRICE decimal(21,9) NULL,
	[DATE] date NULL,
	[SOURCE] nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLIENT_SEC_TYPE nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLIENT_SEC_TYPE2 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CD_INSTMT_TYPE nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT_HANT nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT_HANS nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ISSUE_COUNTRY nvarchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COUPON decimal(9,6) NULL,
	COUP_FREQ char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MATURITY date NULL,
	ISSUER nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MUNI_STATE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PUT_CALL nvarchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EXERCISE_TYPE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OPTION_STRIKE decimal(10,0) NULL,
	UNDERLYING_ID nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_ID_TYPE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_DESCRIPTION nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_PRICE decimal(10,0) NULL,
	CONTRACT_SIZE decimal(10,0) NULL,
	RIC nvarchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OCC nvarchar(21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FX_TRADE_DATE date NULL,
	FX_TRADE_CURRENCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NDF_TYPE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONTRACT_CODE nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STANDARD_CONTRACT char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ACCRUAL_DT date NULL,
	RED_CODE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EFFECTIVE_DATE date NULL,
	COUP_FREQ_PAY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COUP_FREQ_RCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY_PAY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY_RCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PAY_LEG nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REC_LEG nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FIXED_RATE decimal(10,0) NULL,
	UNDERLYING_TERM decimal(10,0) NULL,
	INDEX_NAME_PAY nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	INDEX_NAME_RVY nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TERM decimal(10,0) NULL,
	INDEX_NAME nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	IRS_TYPE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PROXY_SECTOR nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ATTR_NAME nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRODUCT_RISK_RATING decimal(1,0) NULL,
	CONSTRAINT PK__SECURITY__DB91FF368B7EDD25_copy16 PRIMARY KEY (SECURITY_MASTER_OID)
);


-- testflow.dbo.BR_SECURITY_MASTER_SMS_2 definition

-- Drop table

-- DROP TABLE testflow.dbo.BR_SECURITY_MASTER_SMS_2;

CREATE TABLE testflow.dbo.BR_SECURITY_MASTER_SMS_2 (
	SECURITY_MASTER_OID bigint NOT NULL,
	CLIENT_ID nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CUSIP nvarchar(9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ISIN nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SEDOL nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TICKER nvarchar(16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRICE decimal(21,9) NULL,
	[DATE] date NULL,
	[SOURCE] nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLIENT_SEC_TYPE nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLIENT_SEC_TYPE2 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CD_INSTMT_TYPE nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT_HANT nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESC_INSTMT_HANS nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ISSUE_COUNTRY nvarchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COUPON decimal(9,6) NULL,
	COUP_FREQ char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MATURITY date NULL,
	ISSUER nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MUNI_STATE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PUT_CALL nvarchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EXERCISE_TYPE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OPTION_STRIKE decimal(10,0) NULL,
	UNDERLYING_ID nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_ID_TYPE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_DESCRIPTION nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNDERLYING_PRICE decimal(10,0) NULL,
	CONTRACT_SIZE decimal(10,0) NULL,
	RIC nvarchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OCC nvarchar(21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FX_TRADE_DATE date NULL,
	FX_TRADE_CURRENCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NDF_TYPE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONTRACT_CODE nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STANDARD_CONTRACT char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ACCRUAL_DT date NULL,
	RED_CODE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EFFECTIVE_DATE date NULL,
	COUP_FREQ_PAY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COUP_FREQ_RCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY_PAY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENCY_RCY nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PAY_LEG nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REC_LEG nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FIXED_RATE decimal(10,0) NULL,
	UNDERLYING_TERM decimal(10,0) NULL,
	INDEX_NAME_PAY nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	INDEX_NAME_RVY nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TERM decimal(10,0) NULL,
	INDEX_NAME nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	IRS_TYPE nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PROXY_SECTOR nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ATTR_NAME nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRODUCT_RISK_RATING decimal(1,0) NULL,
	CONSTRAINT PK__SECURITY__DB91FF368B7EDD25_copy17 PRIMARY KEY (SECURITY_MASTER_OID)
);

-- testflow.dbo.TABLE_SWITCH_LOG definition

-- Drop table

-- DROP TABLE testflow.dbo.TABLE_SWITCH_LOG;

CREATE TABLE testflow.dbo.TABLE_SWITCH_LOG (
	table_switch_log_oid int IDENTITY(1,1) NOT NULL,
	target_table varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	operation_type varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	business_date date NULL,
	table_suffix varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	create_datetime datetime NULL,
	create_user varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[type] varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	is_valid char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	last_mod_datetime datetime NULL,
	last_mod_user varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK__TABLE_SW__BEF806C027F3216E PRIMARY KEY (table_switch_log_oid)
);


-- testflow.dbo.TMP_SECURITY_LISTS_1 definition

-- Drop table

-- DROP TABLE testflow.dbo.TMP_SECURITY_LISTS_1;

CREATE TABLE testflow.dbo.TMP_SECURITY_LISTS_1 (
	ID int IDENTITY(1,1) NOT NULL,
	CREATE_TIME datetime NOT NULL,
	CLIENT_ID nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LIST_TAG nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LIST_VALUE nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DATA_SOURCE nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK__BR_SECUR__3214EC2705D2AF23_copy1 PRIMARY KEY (ID)
);


-- testflow.dbo.TMP_SECURITY_LISTS_2 definition

-- Drop table

-- DROP TABLE testflow.dbo.TMP_SECURITY_LISTS_2;

CREATE TABLE testflow.dbo.TMP_SECURITY_LISTS_2 (
	ID int IDENTITY(1,1) NOT NULL,
	CREATE_TIME datetime NOT NULL,
	CLIENT_ID nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LIST_TAG nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LIST_VALUE nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DATA_SOURCE nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK__BR_SECUR__3214EC2705D2AF23_copy1_copy1 PRIMARY KEY (ID)
);
