
#  Redis 日志
/opt/project/PAP/redis/logs/*.log {
    daily
    rotate 1
    missingok
    notifempty
    dateext
    dateformat -%Y%m%d
    nocompress
    copytruncate
    postrotate

        HOSTNAME=$(hostname)
        MODULE="redis"
        DATETIME=$(date +\%Y\%m\%d)
        ARCHIVE_DIR="/LOG"
        ROTATED_FILES=$(find /opt/project/PAP/redis/logs/ -name "*.log-${DATETIME}" 2>/dev/null)

        if [ -n "${ROTATED_FILES}" ]; then
            tar -czf "${ARCHIVE_DIR}/${HOSTNAME}.${MODULE}.${DATETIME}.tar.gz" -C /opt/project/PAP/redis/logs $(for f in ${ROTATED_FILES}; do basename "$f"; done)
        fi
    endscript
}

#  Nginx 日志
/opt/project/PAP/nginx/logs/*.log {
        daily
        rotate 1
        missingok
        notifempty
        dateext
        dateformat -%Y%m%d
        nocompress
        sharedscripts
        postrotate

            HOSTNAME=$(hostname)
            MODULE="nginx"
            DATETIME=$(date +\%Y\%m\%d)
            ARCHIVE_DIR="/LOG"

            [ -f /opt/project/PAP/nginx/logs/nginx.pid ] && kill -USR1 $(cat /opt/project/PAP/nginx/logs/nginx.pid) 2>/dev/null || true

            ROTATED_FILES=$(find /opt/project/PAP/nginx/logs/ -name "*.log-${DATETIME}" 2>/dev/null)
            if [ -n "${ROTATED_FILES}" ]; then
                tar -czf "${ARCHIVE_DIR}/${HOSTNAME}.${MODULE}.${DATETIME}.tar.gz" -C /opt/project/PAP/nginx/logs $(for f in ${ROTATED_FILES}; do basename "$f"; done)
            fi
        endscript
}

#  定期Shell脚本日志
/opt/project/PAP/IHUB/back-end/server*.log {
    daily
    rotate 1
    missingok
    notifempty
    dateext
    dateformat -%Y%m%d
    nocompress
    copytruncate
    postrotate

            HOSTNAME=$(hostname)
            MODULE="shell"
            DATETIME=$(date +\%Y\%m\%d)
            ARCHIVE_DIR="/LOG"
            ROTATED_FILES=$(find /opt/project/PAP/IHUB/back-end -name "*.log-${DATETIME}" 2>/dev/null)
            if [ -n "${ROTATED_FILES}" ]; then
                tar -czf "${ARCHIVE_DIR}/${HOSTNAME}.${MODULE}.${DATETIME}.tar.gz"  -C /opt/project/PAP/IHUB/back-end $(for f in ${ROTATED_FILES}; do basename "$f"; done)
            fi
    endscript
}